[package]
name = "wasmi-async"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = { workspace = true }
getrandom = { workspace = true }
runtime = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
wasmi = { workspace = true }
