[package]
name = "test-plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmi-pdk = { path = "../wasmi-pdk" }
serde = {version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
rand = "0.9.2"
tokio = { version = "1", features = ["rt", "time", "sync", "macros"] }