[package]
name = "test-plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmi-pdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }