[package]
name = "tlock-api"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmi-pdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
alloy = { workspace = true }
uuid = { workspace = true }