[package]
name = "tlock-alloy"
version = "0.1.0"
edition = "2024"

[dependencies]
tlock-pdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
alloy = { workspace = true }
tower-service = { workspace = true }

[build]
target = "wasm32-wasip1"
