[package]
name = "tlock-hdk"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { workspace = true }
tlock-api = { workspace = true }
tlock-pdk = { workspace = true }
tracing = { workspace = true }
wasmi-plugin-hdk = { workspace = true }
wasmi-plugin-pdk = { workspace = true }