[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo-timers = { workspace = true }
web-time = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.47.1", features = ["rt", "macros"] }
